version: '2'

services:
    app:
      build:
        context: ./
        dockerfile: server/Dockerfile
      restart: always
      ports:
        - "8090:8080"
      networks:
        - moonbase
      volumes:
        - ./server/src:/server/src
        - ./server/.env:/server/.env
        - lnd_data:/data
      # environment:
      #   - GRPC_VERBOSITY=DEBUG
      #   - GRPC_TRACE=all
      links:
        - mongo

    mongo:
      image: 'mongo:3.6.3'
      working_dir: '/home/db'
      networks:
        - moonbase

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: docker/btcd
      volumes:
        - shared:/rpc
        - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        networks:
          - moonbase
        entrypoint: ["./start-btcd.sh"]

    lnd:
        image: lnd
        build:
          context: ./
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG=trace
        volumes:
            - shared:/rpc
            - lnd_data:/data
        networks:
          - moonbase
        entrypoint: ["./start-lnd.sh"]


volumes:
  lnd_data:
    driver: local
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local
  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

networks:
  moonbase:
